# Generated by Django 5.0.1 on 2024-01-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=32)),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("pasword", models.CharField(max_length=32)),
                ("user_email", models.CharField(max_length=32)),
            ],
        ),
    ]
