# Generated by Django 5.0.1 on 2024-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0006_userboard"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userboard",
            constraint=models.UniqueConstraint(
                fields=("user", "board"), name="composite_key_constraint"
            ),
        ),
    ]
