# Generated by Django 5.0.1 on 2024-01-19 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="pasword",
            new_name="password",
        ),
    ]
