# Generated by Django 5.0.1 on 2024-01-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_rename_pasword_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                ("board_name", models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=32)),
                ("task_desc", models.TextField(max_length=128)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("task_status", models.CharField(max_length=16)),
                (
                    "board_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.board",
                    ),
                ),
            ],
        ),
    ]
