# Generated by Django 5.0.1 on 2024-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0007_userboard_composite_key_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.CharField(default="", max_length=32),
        ),
    ]
