# Generated by Django 5.0.1 on 2024-01-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0008_task_assigned_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.board",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Home.user",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserBoard",
        ),
    ]
