# Generated by Django 5.0.1 on 2024-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0009_boarduser_delete_userboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=4096),
        ),
    ]
